version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - C:/Users/deul4/react/dev-erp-system/frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: ["npm", "start"]
    stdin_open: true
  
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/deul4/react/dev-erp-system/backend:/app #로컬 backend 폴더와 컨테이너를 연결하는 설정값으로, 로컬 backend 디렉토리 경로 작성해서 설정.
    environment:
      DJANGO_SETTINGS_MODULE: testPj.settings  # Django의 설정 파일을 지정
      PYTHONUTF8: 1
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    stdin_open: true
    depends_on:
      - db  # DB 서비스가 있으면 해당 서비스가 준비된 후 백엔드를 실행

  db: #필요할 경우 사용 - 현재 postgreSQL 서비스로 백엔드와 db를 연결하도록 되어 있음.
    image: postgres
    ports:
      - "5432:5432"  # PostgreSQL 기본 포트
    environment:
      POSTGRES_DB: test  # 사용할 DB 이름
      POSTGRES_USER: new  # DB 사용자 이름
      POSTGRES_PASSWORD: hs0129  # DB 비밀번호
      PYTHONUTF8: 1  # Python UTF-8 강제 설정
      PGCLIENTENCODING: UTF8  # PostgreSQL 클라이언트 인코딩 설정
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 데이터베이스 데이터를 로컬에 저장
volumes:
  postgres_data: