import { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import { apiMethods } from '../utils/api.js';
import DynamicTableChild from '../utils/DynamicTableChild.js';
import { Modal, Button, Form, Row, Col } from 
"react-bootstrap";

const BizOppHistory = ({ show, onHide }) => {
    const [data, setData] = useState([]);
    const [errMsg, setErrMsg] = useState('');
    const [v_handlingHtml, setVHandlingHtml] = useState(null);
    // const endpoint = 'select-biz-opp2/'
    const endpoint = 'select-biz-opp1/'

    // ================= get ================= 
    const f_handlingData = async (method, endpoint, input = null) => {
        try {
            // 유효값 검사
            // ..

            const response = await apiMethods[method](endpoint, input);
            // const response = await apiMethods.get(endpoint);
            // console.log(response.data.retrieve_biz_opp);
            setData(response);
            // updateUI();
            return response;
        } catch (error) {
            setErrMsg(`f_handlingData(${method}) error! ${error.message}`);
            throw error;
        }
    }
/*     if (show) {
        console.log('모달 열림!');
        f_handlingData();
        return;
    } */
    // ================= POST 끝 ================= 
    
    const sampleData = {
        "data": {
            "search_headquarters": [
            {
                "dept_id": "1000000",
                "dept_name": "AJ ICT",
                "high_dept_id": null,
                "mgt_use_dept_id": null,
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-19T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1100000",
                "dept_name": "대표이사",
                "high_dept_id": "1000000",
                "mgt_use_dept_id": "91000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-19T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1110000",
                "dept_name": "경영관리본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "92000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120000",
                "dept_name": "DELL사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "97100",
                "remark": "test임.",
                "create_user": "leecj",
                "create_date": "2024-11-21T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130000",
                "dept_name": "전략사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "97200",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-22T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140000",
                "dept_name": "CC사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "95000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-23T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1150000",
                "dept_name": "신사업추진본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "98000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-24T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "search_team": [
            {
                "dept_id": "1110100",
                "dept_name": "경영관리팀",
                "high_dept_id": "1110000",
                "mgt_use_dept_id": "9201",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-26T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1110200",
                "dept_name": "리스크관리팀",
                "high_dept_id": "1110000",
                "mgt_use_dept_id": null,
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-26T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120100",
                "dept_name": "영업1팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9711",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-27T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120200",
                "dept_name": "영업2팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9712",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-28T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120300",
                "dept_name": "영업3팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9713",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-29T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130100",
                "dept_name": "전략사업1팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9721",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-30T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130200",
                "dept_name": "전략사업2팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9722",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-01T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130300",
                "dept_name": "전략사업3팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9723",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-02T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140100",
                "dept_name": "본부장",
                "high_dept_id": "1140000",
                "mgt_use_dept_id": "9509",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-03T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140200",
                "dept_name": "운영팀",
                "high_dept_id": "1140000",
                "mgt_use_dept_id": "9501",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-04T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1150100",
                "dept_name": "신사업추진팀",
                "high_dept_id": "1150000",
                "mgt_use_dept_id": "9801",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-05T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "search_commonness_pro": [
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0001",
                "great_classi_name": "진행률",
                "small_classi_name": "10%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0002",
                "great_classi_name": "진행률",
                "small_classi_name": "30%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0003",
                "great_classi_name": "진행률",
                "small_classi_name": "50%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0004",
                "great_classi_name": "진행률",
                "small_classi_name": "70%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0005",
                "great_classi_name": "진행률",
                "small_classi_name": "90%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0006",
                "great_classi_name": "진행률",
                "small_classi_name": "100%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "retrieve_biz_opp": [
            {
                "biz_opp_id": "20240001",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240002",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240003",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240004",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240005",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240006",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240007",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240008",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240009",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240010",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240011",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240012",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240013",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240014",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240015",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240016",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240017",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240018",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240019",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240020",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240021",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240022",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240023",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240024",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240025",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240026",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240027",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240028",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240029",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240030",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240031",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240032",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240033",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ]
        },
        "status": {
            "STATUS": "SUCCESS",
            "MESSAGE": "조회되었습니다."
        }
    }
   
    // -------------- 세션 대체용 userId 송신 -------------- 
    const auth = useSelector((state) => state.auth);
    // console.log(auth);
    const userCheck = {
        a_session_user_id: auth.userId,
    }

    useEffect(() => {
        // console.log("userCheck: ", userCheck);
        f_handlingData('post', endpoint, userCheck);
        /* f_handlingData('get', endpoint).then(response => {
            console.log("데이터 로드 완료:", response);
        }).catch(error => {
            console.error("데이터 로드 실패:", error);
        }); */
    }, [endpoint]);
    // -------------- 세션 대체용 userId 송신 끝 -------------- 


    useEffect(() => {
        // console.log(endpoint, data, data.data);
        const updateUI = () => {        
            if (!data.data?.retrieve_biz_opp?.length > 0) {
                console.log("아직 데이터 안 들어왔어요...");
                return <div>Loading...</div>;
            } else {
                console.log('이제 들어왔어요!');
                setVHandlingHtml(
                    <Modal size='xl' fullscreen show={show} onHide={onHide}>
                        <Modal.Header closeButton>
                            <Modal.Title className='fs-3'>
                                사업 (기회) 이력 조회
                            </Modal.Title>
                        </Modal.Header> 
                        <Modal.Body>
                            <Button variant="info" className='btnLeft'>조회</Button>
                            <div className='modalcntnt'>
                                <div className='bizoppHistoryArea'>
                                    <DynamicTableChild v_componentName={'bizOppHistory'} v_propsData={data}/>
                                </div>
                            </div>
                        </Modal.Body>
                        <Modal.Footer className="btnArea justify-content-center">
                            <Button variant="secondary" onClick={onHide}>
                            닫기
                            </Button>
                        </Modal.Footer>
                    </Modal>
                )
            
            }
        };
        updateUI();
    }, [data, show, onHide]);
  
    return (
        <div id='bizOppHistory'>
            {v_handlingHtml}
        </div>
    )
}

export default BizOppHistory;