import { useState, useEffect } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useSelector } from 'react-redux';

import { apiMethods } from '../utils/api.js';
import { login } from '../index.js';
import InputField from '../utils/InputField.js';
import DynamicTable from '../utils/DynamicTable.js';
import { Button } from 'react-bootstrap';
import BizOppDetail from './BizOppDetail.js';
import roots from '../utils/datas/Roots.js';

import InputFieldDetail from '../utils/InputFieldDetail.js';

const BizOpp = () => {
    // const location = useLocation();
    const [data, setData] = useState([]);
    const [errMsg, setErrMsg] = useState('');
    const endpoint = roots.bizopp.endpoint;
    
    const [showModal, setShowModal] = useState(false);
    const openModal = () => setShowModal(true);
    const closeModal = () => setShowModal(false);
    /*-
    데이터 요청 흐름
    1. get(endpoint) 호출 → api.request('get', url) 호출.
    2. api.request에서 axios를 통해 서버에 요청을 보냄.
    3. 서버 응답 객체에서 response.data를 추출하고 반환.
    4. get 함수가 response.data를 그대로 반환.
    -*/

    // const navigate = useNavigate();
    const [returnMsg, setReturnMsg] = useState(null);
    const sampleData = {
        "data": {
            "search_headquarters": [
            {
                "dept_id": "1000000",
                "dept_name": "AJ ICT",
                "high_dept_id": null,
                "mgt_use_dept_id": null,
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-19T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1100000",
                "dept_name": "대표이사",
                "high_dept_id": "1000000",
                "mgt_use_dept_id": "91000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-19T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1110000",
                "dept_name": "경영관리본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "92000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120000",
                "dept_name": "DELL사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "97100",
                "remark": "test임.",
                "create_user": "leecj",
                "create_date": "2024-11-21T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130000",
                "dept_name": "전략사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "97200",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-22T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140000",
                "dept_name": "CC사업본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "95000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-23T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1150000",
                "dept_name": "신사업추진본부",
                "high_dept_id": "1100000",
                "mgt_use_dept_id": "98000",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-24T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "search_team": [
            {
                "dept_id": "1110100",
                "dept_name": "경영관리팀",
                "high_dept_id": "1110000",
                "mgt_use_dept_id": "9201",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-26T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1110200",
                "dept_name": "리스크관리팀",
                "high_dept_id": "1110000",
                "mgt_use_dept_id": null,
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-26T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120100",
                "dept_name": "영업1팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9711",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-27T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120200",
                "dept_name": "영업2팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9712",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-28T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1120300",
                "dept_name": "영업3팀",
                "high_dept_id": "1120000",
                "mgt_use_dept_id": "9713",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-29T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130100",
                "dept_name": "전략사업1팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9721",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-11-30T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130200",
                "dept_name": "전략사업2팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9722",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-01T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1130300",
                "dept_name": "전략사업3팀",
                "high_dept_id": "1130000",
                "mgt_use_dept_id": "9723",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-02T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140100",
                "dept_name": "본부장",
                "high_dept_id": "1140000",
                "mgt_use_dept_id": "9509",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-03T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1140200",
                "dept_name": "운영팀",
                "high_dept_id": "1140000",
                "mgt_use_dept_id": "9501",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-04T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "dept_id": "1150100",
                "dept_name": "신사업추진팀",
                "high_dept_id": "1150000",
                "mgt_use_dept_id": "9801",
                "remark": null,
                "create_user": "leecj",
                "create_date": "2024-12-05T14:47:08",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "search_commonness_pro": [
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0001",
                "great_classi_name": "진행률",
                "small_classi_name": "10%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0002",
                "great_classi_name": "진행률",
                "small_classi_name": "30%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0003",
                "great_classi_name": "진행률",
                "small_classi_name": "50%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0004",
                "great_classi_name": "진행률",
                "small_classi_name": "70%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0005",
                "great_classi_name": "진행률",
                "small_classi_name": "90%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "great_classi_code": "PRO",
                "small_classi_code": "0006",
                "great_classi_name": "진행률",
                "small_classi_name": "100%",
                "explanation": null,
                "create_user": "leecj",
                "create_date": "2024-11-20T11:04:09.312",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ],
            "retrieve_biz_opp": [
            {
                "biz_opp_id": "20240001",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240002",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240003",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240004",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240005",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240006",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240007",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240008",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240009",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240010",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240011",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240012",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240013",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240014",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240015",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240016",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240017",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240018",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240019",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240020",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240021",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240022",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240023",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240024",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240025",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240026",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240027",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240028",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240029",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240030",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240031",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "2024년 연구소시스템 노후 Infra(Server, Storage) 교체 추진(IDEMS)",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 0,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": false,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240032",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            },
            {
                "biz_opp_id": "20240033",
                "biz_opp_clone_no": 1,
                "biz_opp_name": "희수",
                "user_id": "bradjung",
                "user_name": "정윤재",
                "change_preparation_dept_id": "97110  ",
                "change_preparation_dept_name": "영업1팀",
                "last_client_com1_code": "COR",
                "last_client_com2_code": "0001",
                "last_client_com1_name": "법인",
                "last_client_com2_name": "현대자동차",
                "sale_com1_code": "COR",
                "sale_com2_code": "0002",
                "sale_com1_name": "법인",
                "sale_com2_name": "현대오토에버",
                "contract_date": "20241030",
                "progress1_rate_code": "PRO",
                "progress2_rate_code": "0006",
                "progress1_rate_name": "진행률",
                "progress2_rate_name": "100%",
                "sale_item_no": "S24166",
                "sale_date": "20241130",
                "sale_amt": 108685000,
                "sale_profit": 11057303,
                "purchase_date": "20240101",
                "purchase_amt": 21555,
                "collect_money_date": null,
                "biz_section1_code": "BIZ",
                "biz_section2_code": "0001",
                "biz_section1_name": "사업 구분",
                "biz_section2_name": "H/W 유통",
                "essential_achievement_tf": true,
                "principal_product1_code": "COR",
                "principal_product2_code": "0002",
                "product1_name": "법인",
                "product2_name": "현대오토에버",
                "dept_id": "1120100",
                "high_dept_id": "1120000",
                "dept_name": "영업1팀",
                "high_dept_name": "DELL사업본부",
                "create_user": "leecj",
                "create_date": "2024-11-26T14:38:45.323",
                "update_user": null,
                "update_date": null,
                "delete_user": null,
                "delete_date": null
            }
            ]
        },
        "status": {
            "STATUS": "SUCCESS",
            "MESSAGE": "조회되었습니다."
        }
    }
    const f_handlingData = async (method, endpoint, input = null) => {
        try {
            const supportedMethods = ['get', 'post', 'put', 'patch', 'del'];
            if (!supportedMethods.includes(method)) {
                throw new Error('Invalid method');
            }
    
            // 상태 업데이트 여부를 결정
            const isUpdateNeeded = ['post', 'put', 'patch', 'del'].includes(method);
            // console.log(isUpdateNeeded, endpoint);
    
            // API 호출
            // apiMethods[method]에서의 [method]: 객체에 동적으로 접근하는 키. method 변수 값에 따라 객체에서 해당 키에 해당하는 값을 동적으로 갖고 온다. 
            // 일반적으로 객체의 프로퍼티를 접근할 때에는 .을 사용하지만, 동적으로 키를 설정할 때에는 []를 사용한다.  apiMethods[method]는 apiMethods.특정method와 같은 의미이다.
            const response = await apiMethods[method](endpoint, input);
            // console.log("response: ", response);
    
            // 상태 업데이트: 데이터 갱신이 필요한 경우에만 호출
            if (isUpdateNeeded) {
                const updatedData = await apiMethods.get(endpoint);
            } 
            console.log(`API Get (수신)\nEndpoint: (BizOpp.js) ${endpoint}\nresponse: `, response);
            if (Array.isArray(response)) {
                alert(response[0].MESSAGE || '로그인 필요');
                setReturnMsg(<Navigate to="/login/"/>);
                return returnMsg;
            } else {
                setData(response);
                return response;
            }
        } catch (error) {
            setErrMsg(`f_handlingData(${method}) error! ${error.message}`);
            throw error;
        }

    };
   
    // -------------- 세션 대체용 userId 송신 -------------- 
    const auth = useSelector((state) => state.auth);
    const userCheck = {
        a_session_user_id: auth.userId,
    }

    useEffect(() => {
        f_handlingData('post', endpoint, userCheck);
        /* f_handlingData('get', endpoint).then(response => {
            console.log("데이터 로드 완료:", response);
        }).catch(error => {
            console.error("데이터 로드 실패:", error);
        }); */
    }, [endpoint]);
    // -------------- 세션 대체용 userId 송신 끝 -------------- 
      
    const [res, setRes] = useState([]);
    return (
        <>
            {returnMsg || ''}
            <h2>사업 (기회) 조회</h2>
            <InputField v_componentName={'bizOpp'} v_propsData={data} setRes={setRes}/>
            <div className='wrap' id='bizOpp'>
                <div className='dataPostArea'>
                    <div className='btnArea d-flex justify-content-end'>
                        <Button variant='success' className='float-right mb-2' onClick={openModal}>사업 (기회) 등록</Button>
                    </div>
                    
                    {/* <DynamicTabletest v_componentName={'bizOpp'} v_propsData={data}/> */}
                    <InputFieldDetail show={showModal} onHide={closeModal} v_componentName={'bizOpp'} v_propsData={data} v_modalPropsData={null}/*  mode={'등록'} *//>
                    {errMsg ? 
                        (<p>{errMsg}</p>) 
                        :   
                        (data.length === 0 ? 
                            (<p>데이터를 불러오는 중입니다...</p>) : 
                            (<DynamicTable v_componentName={'bizOpp'} v_propsData={data} res={res} />)
                            // ('')
                        )
                    }
                </div>
            </div>
        </>
    )
}
export default BizOpp;